version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=notes_app
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    # Delay app startup to ensure database is fully ready
    command: >
      sh -c "sleep 10 && npm run dev"

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
     # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=notes_app
    restart: unless-stopped
    ports:
      - "3306"

volumes:
  mysql_data: